---
- name: importation des variables
  include_vars:
    dir: defaults
    file: "{{ env }}.yml"

- name: installing lvm2
  yum:
    name: "lvm2"
    state: "present"
  become: true

- include: groups_users_directories.yml

- include: manage_lvm.yml

- include: manage_lvm_rollback.yml

- include: groups_users_directories_rollback.yml
