---
- name: manage_lvm | creation des groupes de volumes
  become: true
  lvg:
    vg: "{{ item['vgname'] }}"
    pvs: "{{ item['disks']|join(',') }}"
    state: "present"
  with_items: "{{ lvm_groups }}"

- name: manage_lvm | creation des volumes logiques
  become: true
  lvol:
    vg: "{{ item[0]['vgname'] }}"
    lv: "{{ item[1]['lvname'] }}"
    size: "{{ item[1]['size'] }}"
    shrink: no
    state: "present"
  register: lvm
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames

- name: manage_lvm | creation des systemes de fichiers sur les volumes logiques
  become: true
  filesystem:
    fstype: ext4
    dev: "/dev/{{ item[0]['vgname'] }}/{{ item[1]['lvname'] }}"
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames

- name: manage_lvm | montage des nouveaux systemes de fichiers
  become: true
  mount:
    name: "{{ item[1]['mntp'] }}"
    src: "/dev/{{ item[0]['vgname'] }}/{{ item[1]['lvname'] }}"
    fstype: ext4
    state: "mounted"
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames

- name: manage_lvm | resizing filesystem
  become: true
  command: resize2fs /dev/{{ item[0]['vgname'] }}/{{ item[1]['lvname'] }}
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames
  when: lvm['changed']
