---
- name: manage_lvm | demontage des systemes de fichiers
  become: true
  mount:
    name: "{{ item['mntp'] }}"
    src: "/dev/{{ item['vgname'] }}/{{ item['lvname'] }}"
    fstype: ext4
    state: "unmounted"
  with_items: "{{ lvm_volumes | reverse | list }}"
  when: not install

- name: manage_lvm | suppression des systemes de fichiers
  become: true
  mount:
    name: "{{ item['mntp'] }}"
    src: "/dev/{{ item['vgname'] }}/{{ item['lvname'] }}"
    fstype: ext4
    state: "absent"
  with_items: "{{ lvm_volumes | reverse | list }}"
  when: not install

- name: manage_lvm | suppression des volumes logiques
  become: true
  lvol:
    vg: "{{ item['vgname'] }}"
    lv: "{{ item['lvname'] }}"
    state: "absent"
    force: yes
  with_items: "{{ lvm_volumes | reverse | list }}"
  when: not install

- name: manage_lvm | suppression des groupes de volumes
  become: true
  lvg:
    vg: "{{ item['vgname'] }}"
    pvs: "{{ item['disks']|join(',') }}"
    state: "absent"
  with_items: "{{ lvm_groups }}"
  when: not install
