---
- name: manage_lvm | creation des groupes de volumes
  become: true
  lvg:
    vg: "{{ item['vgname'] }}"
    pvs: "{{ item['disks']|join(',') }}"
    state: "present"
  with_items: "{{ lvm_groups }}"
  when: install

- name: manage_lvm | creation des volumes logiques
  become: true
  lvol:
    vg: "{{ item['vgname'] }}"
    lv: "{{ item['lvname'] }}"
    size: "{{ item['size'] }}"
    shrink: no
    state: "present"
  register: lvm
  with_items: "{{ lvs }}"
  when: install

- name: manage_lvm | creation des systemes de fichiers sur les volumes logiques
  become: true
  filesystem:
    fstype: ext4
    dev: "/dev/{{ item['vgname'] }}/{{ item['lvname'] }}"
  with_items: "{{ lvs }}"
  when: install

- name: manage_lvm | montage des nouveaux systemes de fichiers
  become: true
  mount:
    name: "{{ item['mntp'] }}"
    src: "/dev/{{ item['vgname'] }}/{{ item['lvname'] }}"
    fstype: ext4
    state: "mounted"
  with_items: "{{ lvs }}"
  when: install

- name: manage_lvm | resizing filesystem
  become: true
  command: resize2fs /dev/{{ item['vgname'] }}/{{ item['lvname'] }}
  with_items: "{{ lvs }}"
  when: lvm['changed'] and install
